# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# permissions:
#   actions: read
#   contents: read

# jobs:
#   main:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ✅
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       # This enables task distribution via Nx Cloud
#       # Run this command as early as possible, before dependencies are installed
#       # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
#       # Uncomment this line to enable task distribution
#       # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

#       # Cache node_modules
#       - name: Setup 💻
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'

#       - name: Install Dependencies 📦
#         run: npm ci --legacy-peer-deps
#       - uses: nrwl/nx-set-shas@v4

#       - name: Build 🛠
#         run: npm run build
#       # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
#       # - run: npx nx-cloud record -- echo Hello World
#       # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
#       # - run: npx nx affected -t lint test build

#       # - name: Deploy to gh pages
#       #   run: |
#       #     npx angular-cli-ghpages --dir=dist/nx-angular-demo --no-silent
#       #   env:
#       #     CI: true
#       #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
